services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 8040:8000
    volumes:
      - ${TUBE_ARCHIVIST_MEDIA_PATH}:/youtube
      - ${TUBE_ARCHIVIST_CACHE_PATH}:/cache
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - archivist-es
      - archivist-redis

  archivist-redis:
    image: redis
    container_name: archivist-redis
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${TUBE_ARCHIVIST_REDIS_PATH}:/data
    expose:
      - "6379"
    depends_on:
      - archivist-es

  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.18.0
    container_name: archivist-es
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${TUBE_ARCHIVIST_ES_PATH}:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"
