services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest@sha256:60e5edcac39172294ad22d55d1b08c2c0a9fe658cad2f2c4d742ae017d7874de
    container_name: sonarr
    env_file:
      - .env
    volumes:
      - ${SONARR_CONFIG_PATH}:/config
      - ${JELLYFIN_TV_PATH}:/tv
      - ${JELLYFIN_BACKED_MEDIA_PATH}:/backedup_media
      - ${DELUGE_DOWNLOADS_PATH}:/downloads
    deploy:
      update_config:
        order: start-first
    ports:
      - 8989:8989
    restart: always
    network_mode: host
    # networks: 
      # - arr 

networks:
  arr: 
    driver: bridge
