services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - .env
    volumes:
      - ${SONARR_CONFIG_PATH}:/config
      - ${JELLYFIN_TV_PATH}:/tv
      - ${DELUGE_DOWNLOADS_PATH}:/downloads
    deploy:
      update_config:
        order: start-first
    ports:
      - 8989:8989
    restart: always
    networks: 
      - arr 

networks:
  arr: 
    driver: bridge
