services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.6
    env_file:
      - .env
    volumes:
      - ${MARIADB_PATH}:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
      interval: 10s
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  memcached:
    container_name: seafile-memcached
    image: bitnami/memcached:latest
    restart: always
    command: memcached -m 256
    healthcheck:
      test: ["CMD", "echo", "stats", "|", "nc", "localhost", "11211"]
      timeout: 20s
      retries: 5
      interval: 10s
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M

  seafile:
    container_name: seafile-server
    image: seafileltd/seafile-mc:latest
    restart: always
    ports:
      - "8800:80"
    env_file:
      - .env
    volumes:
      - ${SEAFILE_DATA_PATH}:/shared
    depends_on:
      mariadb:
        condition: service_healthy
      memcached:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

networks:
  default:
    name: seafile_network
