services:
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest@sha256:d3e9307b320b6772749a2cf8fc2712e9e824c4930b034680ad4d08a9e2f25884
    env_file:
      - .env
    volumes:
      - ${PROWLARR_CONFIG_PATH}:/config
    deploy:
      update_config:
        order: start-first
    ports:
      - 9696:9696
    restart: always
    networks:
      - arr
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1:9696/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 45s

networks:
  arr:
    driver: bridge
