services:
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest@sha256:643220338204525524db787ff38a607261597f49d1f550694acdb3e908e2b43e
    env_file:
      - .env
    volumes:
      - ${PROWLARR_CONFIG_PATH}:/config
    deploy:
      update_config:
        order: start-first
    ports:
      - 9696:9696
    restart: always
    networks: 
      - arr 

networks:
  arr: 
    driver: bridge
