services:
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest@sha256:475853535de3de8441b87c1457c30f2e695f4831228b12b6b7274e9da409d874
    env_file:
      - .env
    volumes:
      - ${PROWLARR_CONFIG_PATH}:/config
    deploy:
      update_config:
        order: start-first
    ports:
      - 9696:9696
    restart: always
    networks:
      - arr
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1:9696/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 45s

networks:
  arr:
    driver: bridge
