services:
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    env_file:
      - .env
    volumes:
      - ${PROWLARR_CONFIG_PATH}:/config
    deploy:
      update_config:
        order: start-first
    ports:
      - 9696:9696
    restart: always
    networks: 
      - arr 

networks:
  arr: 
    driver: bridge
