services:
  gatus:
    container_name: gatus
    image: twinproduction/gatus:latest@sha256:951ca254f7caa23cc9d417a90b74efc4b76efd896f2ce63d56ff00e7fd168e32
    ports:
      - 9900:8080
    env_file:
      - .env
    volumes:
      - ${GATUS_CONFIG_PATH}:/config
      - ${GATUS_DATA_PATH}:/data
    restart: always
