services:
  gatus:
    container_name: gatus
    image: twinproduction/gatus:latest@sha256:7610bbe2e04db0547ed2bf57f57c9ade4d9b05fff9cbba6dc40c41a494ba2e39
    ports:
      - 9900:8080
    env_file:
      - .env
    volumes:
      - ${GATUS_CONFIG_PATH}:/config
      - ${GATUS_DATA_PATH}:/data
    restart: always
