services:
  gatus:
    container_name: gatus
    image: twinproduction/gatus:latest@sha256:9ff09fe5eb5e96b7f2126dc95b375a87a7bc16380d5cb9d798af4e0ef36f0049
    ports:
      - 9900:8080
    env_file:
      - .env
    volumes:
      - ${GATUS_CONFIG_PATH}:/config
      - ${GATUS_DATA_PATH}:/data
    restart: always
