services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest@sha256:d0db2f5b7ab9907269f76f02bf7d96b95fe7f8e20c82bc60310dd2b8530c2868
    container_name: heimdall
    env_file:
      - .env
    volumes:
      - ${HEIMDALL_CONFIG_PATH}:/config
    deploy:
      update_config:
        order: start-first
    ports:
      - 8082:80
    restart: always
