services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest@sha256:0694415ee12a42b362c291b0f77dc2b42eb4bc0877bda26253c9c8a6d79dab01
    container_name: heimdall
    env_file:
      - .env
    volumes:
      - ${HEIMDALL_CONFIG_PATH}:/config
    deploy:
      update_config:
        order: start-first
    ports:
      - 8082:80
    restart: always
