services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest@sha256:615557da71b2b4efdc983e40168fb671f30716183d6988126e24cd226ddd71b5
    container_name: heimdall
    env_file:
      - .env
    volumes:
      - ${HEIMDALL_CONFIG_PATH}:/config
    deploy:
      update_config:
        order: start-first
    ports:
      - 8082:80
    restart: always
