services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    env_file:
      - .env
    volumes:
      - ${VAULTWARDEN_DATA_PATH}:/data/
    deploy:
      update_config:
        order: start-first
    ports:
      - "8060:80"
