services:
  filestash:
    container_name: filestash
    image: machines/filestash
    env_file:
      - .env
    volumes:
    - ${FILESTASH_FILE_SYSTEM_PATH}:/data
    - ${JELLYFIN_MOVIES_PATH}:/jellyfin
    - ${ANDROID_FS_PATH}:/androidfs
    - filestash_state:/app/data/state/
    deploy:
      update_config:
        order: start-first
    ports:
    - "8334:8334"
    restart: always

volumes:
  filestash_state: {}
