services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - .env
    volumes:
      - ${RADARR_CONFIG_PATH}:/config
      - ${JELLYFIN_MOVIES_PATH}:/movies
      - ${DELUGE_DOWNLOADS_PATH}:/downloads

      # - /mnt/ssd1/radarr/config:/config
      # - /mnt/ssd1/jellyfin/media/movies/:/movies
      # - /mnt/ssd1/downloads/:/downloads
    deploy:
      update_config:
        order: start-first
    ports:
      - 7878:7878
    restart: always
    networks: 
      - arr 

networks:
  arr: 
    driver: bridge
