services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - .env
    volumes:
      - ${RADARR_CONFIG_PATH}:/config
      - ${JELLYFIN_MOVIES_PATH}:/movies
      - ${JELLYFIN_BACKED_MEDIA_PATH}:/backedup_media
      - ${DELUGE_DOWNLOADS_PATH}:/downloads
    deploy:
      update_config:
        order: start-first
    ports:
      - 7878:7878
    restart: always
    networks: 
      - arr 

networks:
  arr: 
    driver: bridge
