services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    volumes:
      - /fs/containers/backrest/data:/data
      - /fs/containers/backrest/config:/config
      - /fs/containers/backrest/cache:/cache
      - /fs/containers/backrest/tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
      - /fs:/fs
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Asia/Kolkata
    ports:
      - "9899:9898"
    restart: always
