services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    env_file:
      - .env
    volumes:
      - ${UPTIME_KUMA_DATA_PATH}:/app/data # Persistent storage for Uptime Kuma data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      update_config:
        order: start-first
    ports:
      - "3001:3001"
    restart: always
