services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest@sha256:b2cbcc02915d176fcd7aeff39c2905d0d95fb31c559aa5bcd3d32164488f25af
    ports:
      - 9902:9090
    volumes:
      - /fs/containers/linkding/data:/etc/linkding/data
    env_file:
      - .env
    restart: always
