services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest@sha256:12ffd6f3b48c5d46543d2f38030de1f476d8dcff5f486eb75c9c7cb5941e7127
    ports:
      - 9902:9090
    volumes:
      - /fs/containers/linkding/data:/etc/linkding/data
    env_file:
      - .env
    restart: always
