services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    ports:
      - 9902:9090
    volumes:
      - /fs/containers/linkding/data:/etc/linkding/data
    env_file:
      - .env
    restart: unless-stopped
