services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest@sha256:8e0d495f10f2ee29919f229ae0b32d92f2b7a5d5339fc6f171f19f3f94b9ed56
    container_name: deluge
    env_file:
      - .env
    volumes:
      - ${DELUGE_CONFIG_PATH}:/config
      - ${DELUGE_DOWNLOADS_PATH}:/downloads
      - ${MEDIA_MOVIES_PATH}:/movies
      - ${MEDIA_TV_PATH}:/tv
    deploy:
      update_config:
        order: start-first
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846
    restart: always
    networks: 
      - arr 

networks:
  arr: 
    driver: bridge
