services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest@sha256:27cf98b7b5c29a7d492210b841aae6a038527e66c4a8657129939527179560d0
    container_name: deluge
    env_file:
      - .env
    volumes:
      - ${DELUGE_CONFIG_PATH}:/config
      - ${DELUGE_DOWNLOADS_PATH}:/downloads
    deploy:
      update_config:
        order: start-first
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846
    restart: always
    networks: 
      - arr 

networks:
  arr: 
    driver: bridge
