services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest@sha256:ee7d7550c5f34e1a906f6748604cf143bd6b04ec7a5a71e01b83b53bd756dccd
    container_name: deluge
    env_file:
      - .env
    volumes:
      - ${DELUGE_CONFIG_PATH}:/config
      - ${DELUGE_DOWNLOADS_PATH}:/downloads
    deploy:
      update_config:
        order: start-first
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846
    restart: always
    networks: 
      - arr 

networks:
  arr: 
    driver: bridge
