services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest@sha256:234ea8d508b2cba26054d0dac9d4c0353435dce483e8b266947d473629774559
    container_name: jellyfin
    env_file:
      - .env
    volumes:
      - ${JELLYFIN_CONFIG_PATH}:/config
      - ${JELLYFIN_MOVIES_PATH}:/data/movies
      - ${JELLYFIN_TV_PATH}:/data/tv
      - ${JELLYFIN_BACKED_MEDIA_PATH}:/data/backedup_media
    deploy:
      update_config:
        order: start-first
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    devices:
      - /dev/dri:/dev/dri
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1:8096/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 60s
