services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest@sha256:313571f253bf1035809f6856bb063904456226ef3899b96e60ee4597b3477246
    container_name: jellyfin
    env_file:
      - .env
    volumes:
      - ${JELLYFIN_CONFIG_PATH}:/config
      - ${JELLYFIN_MOVIES_PATH}:/data/movies
      - ${JELLYFIN_TV_PATH}:/data/tv
      - ${JELLYFIN_BACKED_MEDIA_PATH}:/data/backedup_media
    deploy:
      update_config:
        order: start-first
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    devices:
      - /dev/dri:/dev/dri
    restart: always
