services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest@sha256:d38a6876b61df32e4da13c0ca61cf2aa0f27afc103abb4ca7ad4e1cf000e17c3
    env_file:
      - .env
    volumes:
      - ${PORTAINER_DATA_PATH}:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      update_config:
        order: start-first
    ports:
      - 9443:9443
      - 9000:9000
    restart: always
volumes:
  data:
