services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest@sha256:c2353b2bd0dbfaa33faa8895222732e8823a4cf5b57ea664ba631ec3e23d842b
    env_file:
      - .env
    volumes:
      - ${PORTAINER_DATA_PATH}:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      update_config:
        order: start-first
    ports:
      - 9443:9443
      - 9000:9000
    restart: always
volumes:
  data:
