services:
  cloudreve:
    image: cloudreve/cloudreve:4.8.0@sha256:a553e5138ffc039388a0b45124189d0dec08f0c9b90d57469dc6240df9bfa452
    container_name: cloudreve-backend
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    ports:
      - "5212:5212"
    env_file:
      - .env
    volumes:
      - ${CLOUDREVE_DATA_PATH}:/cloudreve/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5212/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgresql:
    image: postgres:18@sha256:073e7c8b84e2197f94c8083634640ab37105effe1bc853ca4d5fbece3219b0e8
    container_name: cloudreve-psql
    restart: always
    env_file:
      - .env
    volumes:
      - ${CLOUDREVE_PSQL_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cloudreve -d cloudreve"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:latest@sha256:acb90ced0bd769b7c04cb4c32c4494ba7b3e0ee068bdbfff0eeb0d31c2a21078
    container_name: cloudreve-redis
    restart: always
    env_file:
      - .env
    volumes:
      - ${CLOUDREVE_REDIS_PATH}:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
