services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    env_file:
      - .env
    volumes:
      # - ${HOME}/bazarr/config:/config
      # - ${HOME}/jellyfin/media/movies:/movies
      # - ${HOME}/jellyfin/media/tv:/tv
      - ${BAZARR_CONFIG_PATH}:/config
      - ${JELLYFIN_MOVIES_PATH}:/movies
      - ${JELLYFIN_TV_PATH}:/tv
    deploy:
      update_config:
        order: start-first
    ports:
      - 6767:6767
    restart: always

networks:
  arr: 
    driver: bridge
