services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest@sha256:d40ee61030a9afafddfdd58d160281b865bfcad7cb66e920116fd6fd40668cbb
    container_name: bazarr
    env_file:
      - .env
    volumes:
      - ${BAZARR_CONFIG_PATH}:/config
      - ${MOVIES_MEDIA_PATH}:/movies
      - ${TV_MEDIA_PATH}:/tv
    deploy:
      update_config:
        order: start-first
    ports:
      - 6767:6767
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1:6767/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 60s

networks:
  arr:
    driver: bridge
