services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest@sha256:7d0a091a63889ce1e4ac4c90595ebd2c50ba5a5df7039a4f4d2be6c2aed6d4ae
    container_name: bazarr
    env_file:
      - .env
    volumes:
      - ${BAZARR_CONFIG_PATH}:/config
      - ${MOVIES_MEDIA_PATH}:/movies
      - ${TV_MEDIA_PATH}:/tv
    deploy:
      update_config:
        order: start-first
    ports:
      - 6767:6767
    restart: always

networks:
  arr: 
    driver: bridge
