services:
  drive:
    image: copyparty/ac:latest@sha256:941de3bf7a0ed45b1f0cc2bd12fdb7c89963745e5ec5f2c9b24fc947699ad8bb
    container_name: drive
    user: "1000:1000"
    ports:
      - 4923:3923
    volumes:
      - /fs/containers/copyparty/drive:/cfg:z
      - /fs/backups/warm/copyparty-drive:/drive:z
    environment:
      LD_PRELOAD: /usr/lib/libmimalloc-secure.so.NOPE
      PYTHONUNBUFFERED: 1
    stop_grace_period: 15s
    restart: always
    # healthcheck:
      # test: ["CMD-SHELL", "wget --spider -q 127.0.0.1:4923/?reset=/._"]
      # interval: 1m
      # timeout: 2s
      # retries: 5
      # start_period: 15s
