services:
  beszel:
    image: henrygd/beszel@sha256:d1326b5cd73838b1d1acc5f1764c4b993c9668aa26df149082695894cb2805ae
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - /fs/containers/beszel/data:/beszel_data

  beszel-agent:
    image: henrygd/beszel-agent@sha256:137f2aefa4f8b06df8a94cc85449da6da2e1977230bfa5fdce9d0119ada19b0a
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /fs/containers/beszel/data/:/var/lib/beszel-agent
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: 45876
      KEY: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILfg+dLw2pLprXM5ZRoQAuh8hc90GXVw26L1aUzk9dOJ'
      TOKEN: 11abd-5b7d93395-119b1c-ed338ab
      HUB_URL: http://100.69.69.69:8090
