services:
  beszel:
    image: henrygd/beszel@sha256:dac99b67c250fe5492d9c6f5d889905fa93726cf8f44eaa7bc0970c7e3ea2eeb
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - /fs/containers/beszel/data:/beszel_data

  beszel-agent:
    image: henrygd/beszel-agent@sha256:67b51e7976da13b7ce15e0270869827d54aa3df8cf0978e240e4105f62395a46
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /fs/containers/beszel/data/:/var/lib/beszel-agent
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: 45876
      KEY: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILfg+dLw2pLprXM5ZRoQAuh8hc90GXVw26L1aUzk9dOJ'
      TOKEN: 11abd-5b7d93395-119b1c-ed338ab
      HUB_URL: http://100.69.69.69:8090
