services:
  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - /fs/containers/beszel/data:/beszel_data
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1:8090/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 30s

  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /fs/containers/beszel/data/:/var/lib/beszel-agent
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: 45876
      KEY: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILfg+dLw2pLprXM5ZRoQAuh8hc90GXVw26L1aUzk9dOJ'
      TOKEN: 11abd-5b7d93395-119b1c-ed338ab
      HUB_URL: http://100.69.69.69:8090
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 45876 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 30s
