services:
  syncthing:
    image: linuxserver/syncthing:latest@sha256:4e3e8de1ada041942b6f34df6d646404a90aa8a2a49a022446ec577c9f8f88ed
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /fs/containers/syncthing/config:/config
      # - /fs/containers/syncthing/data:/data
      - /fs/backups:/data
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # Sync protocol
      - 22000:22000/udp # Sync protocol
      - 21027:21027/udp # Discovery
    restart: always
