services:
  syncthing:
    image: linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /fs/containers/syncthing/config:/config
      - /fs/containers/syncthing/data:/data
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # Sync protocol
      - 22000:22000/udp # Sync protocol
      - 21027:21027/udp # Discovery
    restart: unless-stopped
