services:
  syncthing:
    image: linuxserver/syncthing:latest@sha256:c426c56a324ff5c50043401ba83ab3ca7e9d0042767269e4526c37048c4c5a26
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /fs/containers/syncthing/config:/config
      # - /fs/containers/syncthing/data:/data
      - /fs/backups:/data
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # Sync protocol
      - 22000:22000/udp # Sync protocol
      - 21027:21027/udp # Discovery
    restart: always
