services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest@sha256:4f4e5f759aa3a9a64305e99188ea1db1ec2944a5e7d290d2b089af5f2f6f48e4
    container_name: flaresolverr
    env_file:
      - .env
    deploy:
      update_config:
        order: start-first
    ports:
      - "${PORT}:8191"
    restart: always
    networks:
      - arr

networks:
  arr: 
    driver: bridge
