services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    env_file:
      - .env
    deploy:
      update_config:
        order: start-first
    ports:
      - "${PORT}:8191"
    restart: always
    networks:
      - arr

networks:
  arr: 
    driver: bridge
