services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest@sha256:7962759d99d7e125e108e0f5e7f3cdbcd36161776d058d1d9b7153b92ef1af9e
    container_name: flaresolverr
    env_file:
      - .env
    deploy:
      update_config:
        order: start-first
    ports:
      - "${PORT}:8191"
    restart: always
    networks:
      - arr

networks:
  arr: 
    driver: bridge
