services:
  ttyd:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ttyd
    ports:
      - "7681:7681"
    volumes:
      - /fs/.ollama:/root/.ollama  # Persist Ollama models and data
      - /fs/containers/ttyd/Modelfile:/root/Modelfile
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: always
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 2G
