services:
  miniflux:
    image: ${MINIFLUX_IMAGE:-miniflux/miniflux:latest@sha256:fd6587a23884c277301307e4d70c196cd0f772fba1720b9e60051fc65a75121e}
    container_name: miniflux
    restart: always
    ports:
      - "9908:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
  db:
    image: postgres:18@sha256:073e7c8b84e2197f94c8083634640ab37105effe1bc853ca4d5fbece3219b0e8
    container_name: miniflux-postgres
    volumes:
      - /fs/containers/minifluxrss/psql:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
